name: Auto Sync Fork

on:
  schedule:
    - cron: '0 16 * * *'   # 每天北京时间 0 点执行（UTC 16 点）
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/free-nodes/v2rayfree.git || true
          git fetch upstream

      - name: Rebase onto upstream/main
        run: |
          git checkout main
          git fetch upstream
          git rebase upstream/main || (git rebase --abort && git reset --hard upstream/main)

      - name: Force push to origin
        run: |
          git push origin main --force
